### ISSUE TITLE
Server crashes immediately when tau grenade explodes

### ISSUE THREAD

**Issue by ghost** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#106]
java.lang.NoSuchMethodError: net.minecraft.world.World.func_175682_a(Lnet/minecraft/util/EnumParticleTypes;ZDDDDDD[I)V
	at com.hbm.entity.projectile.EntityBullet.func_70071_h_(EntityBullet.java:577)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Alcatergit** [comment]
Looks like some other mod has removed or overwritten the world.spawnParticle() method. TF
If other mods mess with minecrafts core code then they are to blame if it stops working.
