### ISSUE TITLE
Fractioning Tower has client-side class referenced server-side; java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by zach2039** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#162]
Looks like the Fractioning Tower is referencing a client-side only class (net/minecraft/client/resources/I18n) on multiplayer server when recipe is set by player:

```
[19:09:31] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_271]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_271]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:840) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_271]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
	at com.hbm.blocks.machine.MachineFractionTower.func_180639_a(MachineFractionTower.java:95) ~[MachineFractionTower.class:1.9.6]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:580) ~[or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:1151) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(CPacketPlayerTryUseItemOnBlock.java:61) ~[ma.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(CPacketPlayerTryUseItemOnBlock.java:13) ~[ma.class:?]
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:16) ~[hv.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_271]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_271]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.resources.I18n
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_271]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_271]
	at com.hbm.blocks.machine.MachineFractionTower.func_180639_a(MachineFractionTower.java:95) ~[MachineFractionTower.class:1.9.6]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:580) ~[or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:1151) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(CPacketPlayerTryUseItemOnBlock.java:61) ~[ma.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(CPacketPlayerTryUseItemOnBlock.java:13) ~[ma.class:?]
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:16) ~[hv.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_271]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_271]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
Caused by: java.lang.NullPointerException
```

Mods in use:

```
AIReducer-1.12.2-0.3.0.jar
AppleCore-mc1.12.2-3.4.0.jar
AppleSkin-mc1.12-1.0.14.jar
AquaAcrobatics-1.15.3.jar
Artifacts-1.12.2-1.2.3.jar
AttributeFix-Forge-1.12.2-1.0.12.jar
AutoRegLib-1.3-32.jar
Baubles-1.12-1.5.2.jar
BedBreakBegone-1.0.2.jar
BetterMineshaftsForge-1.12.2-2.2.1.jar
BiomesOPlenty-1.12.2-7.0.1.2445-universal.jar
BlockOverlayFix-1.12.2-1.0.0.jar
Born In A Barn V1.8-1.12-1.1.jar
CTM-MC1.12.2-1.0.2.31.jar
Charm-1.12.2-1.4.1.jar
Chisel-MC1.12.2-1.0.2.45.jar
ChunkAnimator-1.12.2-1.2.1.jar
Clumps-3.1.2.jar
CoFHCore-1.12.2-4.6.6.1-universal.jar
CoFHWorld-1.12.2-1.4.0.1-universal.jar
CodeChickenLib-1.12.2-3.2.3.358-universal.jar
ContentTweaker-1.12.2-4.10.0.jar
Controlling-3.0.12.2.jar
CookingForBlockheads_1.12.2-6.5.0.jar
CraftTweaker2-1.12-4.1.20.689.jar
CreativeCore_v1.10.70_mc1.12.2.jar
DefaultOptions_1.12.2-9.2.8.jar
DoomlikeDungeons-1.14.12-MC1.12.2.jar
DynamicLights-1.12.2.jar
DynamicSurroundings-1.12.2-3.6.1.0.jar
EnchantmentDescriptions-1.12.2-1.1.15.jar
EntityCulling-1.12.2-6.3.1.jar
FamiliarFauna-1.12.2-1.0.11.jar
FancyBlockParticles-1.12.x-2.4.1.jar
Fluidlogged-API-v2.2.4-mc1.12.2.jar
ForgeMultipart-1.12.2-2.6.2.83-universal.jar
Friendly-Chests-v1.0.3-mc1.12.2.jar
Glymworld-LushCaves-v1.4.1.jar
HMBFixes-1.12.2-12.1.0.jar
HammerLib-1.12.2-2.0.6.32.jar
HelpFixer-1.12.1-1.5.18.jar
Hwyla-1.8.26-B41_1.12.2.jar
InfernalMobs-1.12.2.jar
Inspirations-1.12.2-0.2.9.jar
InventoryTweaks-1.63.jar
ItemPhysic_Full_1.4.37_mc1.12.2.jar
IvToolkit-1.3.3-1.12.jar
JustEnoughResources-1.12.2-0.9.2.60.jar
LegendaryTooltips-1.12.2-1.1.10.jar
Locks-1.12.2-3.0.0.jar
Login_Shield-1.12.2-6-g5654706.jar
LootTweaker-0.3.1+MC1.12.2.jar
MTLib-3.0.7.jar
Mantle-1.12-1.3.3.55.jar
MmmMmmMmmMmm-1.12-1.14.jar
MoBends_1.12.2-1.2.1-19.12.21.jar
Morpheus-1.12.2-3.5.106.jar
MouseTweaks-2.10-mc1.12.2.jar
MrTJPCore-1.12.2-2.1.4.43-universal.jar
MultiMine-1.12.2.jar
NTM-Extended-1.12.2-1.9.6.jar
NetherPortalFix_1.12.1-5.3.17.jar
OceanicExpanse-1.0.6.jar
OpenComputers-MC1.12.2-1.8.2+b4abbf9.jar
OreLib-1.12.2-3.6.0.1.jar
Pam's HarvestCraft 1.12.2zg.jar
Placebo-1.12.2-1.6.0.jar
PortalDupeBegone-1.0.0.jar
PotionCore-1.9_for_1.12.2.jar
PotionFingers-r1.0-8.jar
ProjectRed-1.12.2-4.9.4.120-Base.jar
ProjectRed-1.12.2-4.9.4.120-compat.jar
ProjectRed-1.12.2-4.9.4.120-fabrication.jar
ProjectRed-1.12.2-4.9.4.120-integration.jar
ProjectRed-1.12.2-4.9.4.120-lighting.jar
ProjectRed-1.12.2-4.9.4.120-mechanical.jar
QualityTools-1.0.7_for_1.12.2.jar
Quark-r1.6-179.jar
RLCombat-1.12.2-2.0.8.jar
RLMixins-1.2.14.jar
RLTweaker-1.12.2-0.5.3.jar
RTG-1.12.2-6.1.0.0-snapshot.1.jar
ReAuth-1.12-Forge-4.0.7.jar
ReachFix-1.12.2-1.0.8.jar
RealBench-1.12.2-1.3.3.jar
RecurrentComplex-1.4.8.4.jar
RedstoneFlux-1.12-2.1.1.1-universal.jar
RenderLib-1.12.2-1.2.8.jar
RoguelikeDungeonsFnarEdition-1.12.2-2.4.4.jar
Ruins-1.12.2.jar
SRParasites-1.12.2v1.9.12.jar
ShieldBreak-1.1.3.jar
SnowRealMagic-1.12.2-0.7.1.jar
SpartanHUDBaubles-1.12.2-1.0.0.jar
SpartanShields-1.12.2-1.5.5.jar
SpartanWeaponry-1.12.2-1.5.3.jar
Surge-1.12.2-2.0.77.jar
ThermalDynamics-1.12.2-2.5.6.1-universal.jar
ThermalExpansion-1.12.2-5.5.7.1-universal.jar
ThermalFoundation-1.12.2-2.6.7.1-universal.jar
Toast Control-1.12.2-1.8.1.jar
ToolBelt-1.12.2-1.9.14.jar
Traverse-1.12.2-1.6.0-69.jar
Trinkets and Baubles-32.4.jar
UniDict-1.12.2-3.0.10.jar
WanionLib-1.12.2-2.9.jar
WearableBackpacks-RLCraft-1.12.2-3.2.6.jar
WolfArmorAndStorage-1.12.2-3.8.0-universal-signed.jar
XPFromHarvest-1.12.2-1.2.0.jar
[1.12]TreeCapitator-client-1.43.0.jar
[1.12]bspkrsCore-universal-7.6.0.1.jar
[___MixinCompat-0.8___].jar
_MixinBootstrap-1.1.0.jar
anvilpatch-1.1.0.jar
astikorcarts-1.12.2-0.1.2.8.jar
base-1.12.2-3.14.0.jar
bettercaves-1.12.2-2.0.4.jar
betternether-0.1.8.6.jar
chunkgenlimiter-1.1.jar
comforts-1.12.2-1.4.1.3.jar
coroutil-1.12.1-1.2.37.jar
craftablechainmail-1.0.jar
culinaryconstruct-1.3.4.jar
defiledlands-1.12.2-1.4.3.jar
foamfix-0.10.15-1.12.2.jar
framevoidpatch-1.0.0.jar
gravestone-1.10.3.jar
jei_1.12.2-4.16.1.301.jar
journeymap-1.12.2-5.7.1.jar
just-enough-harvestcraft-1.12.2-1.7.2.jar
lostcities-1.12-2.0.22.jar
lycanitesmobs-1.12.2-2.0.8.9.jar
modtweaker-4.0.20.11.jar
obfuscate-0.4.2-1.12.2.jar
pamscookables-1.1.jar
particleculling-1.12.2-v1.4.1.jar
phosphor-1.12.2-0.2.6+build50-universal.jar
pigstep-1.12.jar
railcraft-12.0.0.jar
railcraft-tweaker-0.2.0.jar
randompatches-1.12.2-1.22.1.10.jar
solcarrot-1.12.2-1.8.4.jar
spark-forge.jar
spartandefiled-1.0.jar
stg-1.12.2-1.2.3.jar
tnt_utilities-mc1.12-1.2.3.jar
trumpetskeleton-1.12-1.0.2.1.jar
tumbleweed-1.12-0.4.7.jar
weaponmaster-multi-forge-1.12.2-3.0.2.jar
weather2-1.12.1-2.6.12.jar
```

**Comment by Alcatergit** [comment]
Fixed it. Will be in next update.
