### ISSUE TITLE
NullPointer at TileEntityDoorGeneric caused by ProjectE mod

### ISSUE THREAD

**Issue by ChrisL97** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#190]
Im hosting a server with my friend when suddenly the server crashed.
```
net.minecraft.util.ReportedException: Ticking block entity
Caused by: java.lang.NullPointerException
        at com.hbm.tileentity.TileEntityDoorGeneric.func_73660_a(TileEntityDoorGeneric.java:66) ~[TileEntityDoorGeneric.class:1.9.7]
        at moze_intel.projecte.gameObjs.items.TimeWatch.speedUpTileEntities(TimeWatch.java:213) ~[TimeWatch.class:?]
        at moze_intel.projecte.gameObjs.items.TimeWatch.updateInPedestal(TimeWatch.java:355) ~[TimeWatch.class:?]
        at moze_intel.projecte.gameObjs.tiles.DMPedestalTile.func_73660_a(DMPedestalTile.java:45) ~[DMPedestalTile.class:?]
```
What caused the crash was that `doorType` was null, and I do place a Dark Matter Pedestal next to a safty door.
Currently I write a if-null-return at the begining of `update()`  at `TileEntityDoorGeneric` and it works pritty well (at least no crash).

**Comment by ChrisL97** [comment]
image attached, the safty door block is null which crashed the games before
![1689093463542](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/63628206/7cb1d347-6d40-40aa-8d1e-66b33721c66d)

**Comment by Alcatergit** [comment]
Fixed in dev. Will be in the next update
