### ISSUE TITLE
idk crash

### ISSUE THREAD

**Issue by username90001** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#22]
crash report
WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  FMLPlugin (albedo-1.12.2-1.1.0.jar)
  LoadingPlugin (AdPother-1.12.2-1.2.22.1-build.0639.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  OTGCorePlugin (OTG-Core.jar)
  LoadingPlugin (AdChimneys-1.12.2-3.5.15.1-build.0630.jar)
  Quark Plugin (Quark-r1.6-179.jar)
  IILoadingPlugin (immersiveintelligence-core-0.2.1.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  MicdoodlePlugin (Galacticraft-1.12.2-4.0.4.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  CorePlugin (ForgeEndertech-1.12.2-4.5.6.0-build.0619.jar)
  DCASMPlugin (HeatAndClimateLib_1.12.2-3.9.3.jar)
  MixinLoaderForge ([[valkyrien-skies-1.1.7-all]].jar)
  CubicChunksCoreMod (CubicChunks-1.12.2-0.0.1007.0-SNAPSHOT-all.jar)
  LootrCore (lootr-1.12.2-0.5.1.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-2.0.0-13.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.8.0-snapshot-20220917+efb20a2.jar)
  MixinBooter (!mixinbooter-7.0.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 12/17/22 7:25 AM
Description: Initializing game

java.lang.NoClassDefFoundError: net/minecraft/client/renderer/RenderGlobal
	at net.minecraftforge.client.ForgeHooksClient.shouldUseVanillaReloadableListener(ForgeHooksClient.java:951)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:131)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:112)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:808)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:247)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.RenderGlobal
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 14 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 16 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in net/minecraft/client/renderer/RenderGlobal::func_180446_a(Lnet/minecraft/entity/Entity;Lnet/minecraft/client/renderer/culling/ICamera;F)V has incompatible changes at opcode 436 in callback net/minecraft/client/renderer/RenderGlobal::onGetPositionOptifine_New.
Expected: [I, D, D, D, Lnet/minecraft/entity/Entity;, D, D, D, Ljava/util/List;, Z, Z, Z, Z, Ljava/util/List;, Ljava/util/List;, Lnet/minecraft/util/math/BlockPos$PooledMutableBlockPos;, Ljava/util/Iterator;, Ljava/lang/Object;]
   Found: [I, D, D, D, Lnet/minecraft/entity/Entity;, D, D, D, Ljava/util/List;, Z, Z, Z, Ljava/util/List;, Ljava/util/List;, Lnet/minecraft/util/math/BlockPos$PooledMutableBlockPos;, Z, Ljava/util/Iterator;, Lnet/minecraft/client/renderer/RenderGlobal$ContainerLocalRenderInformation;]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:487)
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:437)
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:264)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:385)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1284)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 21 more

(MixinBooter) Mixins in Stacktrace:
	net.minecraft.client.Minecraft:
		org.valkyrienskies.mixin.client.MixinMinecraft (mixins.valkyrienskies.json)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.client.ForgeHooksClient.shouldUseVanillaReloadableListener(ForgeHooksClient.java:951)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:131)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:112)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:808)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:247)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Alcatergit** [comment]
It does not seem to be a crash caused by this mod
