### ISSUE TITLE
Rightclicking gas mask filter with power armor helment which does not contain gas mask crashes game

### ISSUE THREAD

**Issue by ghost** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#235]
java.lang.ClassCastException: net.minecraft.item.ItemAir cannot be cast to com.hbm.items.armor.ItemArmorMod
	at com.hbm.handler.ArmorModHandler.applyMod(ArmorModHandler.java:87)
	at com.hbm.items.tool.ItemFilter.func_77659_a(ItemFilter.java:45)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:217)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187101_a(PlayerControllerMP.java:511)
	at net.optifine.override.PlayerControllerOF.func_187101_a(PlayerControllerOF.java:80)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1597)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1808)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

**Comment by Alcatergit** [comment]
Can't replicate that in 1.9.8 - what filter and armor were you using?

**Comment by Alcatergit** [comment]
Should be fixed
