### ISSUE TITLE
After putting second reflector on rbmk with digamma fuel rod, world crashes on join

### ISSUE THREAD

**Issue by ghost** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#242]
[16:48:53] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:773) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279) ~[chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_382]
Caused by: java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388) ~[?:1.8.0_382]
	at com.hbm.tileentity.machine.rbmk.TileEntityRBMKBase.jump(TileEntityRBMKBase.java:129) ~[TileEntityRBMKBase.class:1.9.8]
	at com.hbm.tileentity.machine.rbmk.TileEntityRBMKBase.func_73660_a(TileEntityRBMKBase.java:114) ~[TileEntityRBMKBase.class:1.9.8]
	at com.hbm.tileentity.machine.rbmk.TileEntityRBMKRod.func_73660_a(TileEntityRBMKRod.java:100) ~[TileEntityRBMKRod.class:1.9.8]
	at net.minecraft.world.World.func_72939_s(World.java:1838) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) ~[MinecraftServer.class:?]
	... 4 more

**Comment by ghost** [comment]
seems to happen every time when putting digamma rod in this
![Screenshot_1](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/87919245/b4f560d1-88df-4ea7-996d-c53ecc02a1eb)

**Comment by Alcatergit** [comment]
Fixed
