### ISSUE TITLE
Server Error When Running V2.0.0

### ISSUE THREAD

**Issue by LukeMedia** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#300]
The previous update works great when running on a Forge server, but with the new version I get the following error:

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from HBM's Nuclear Tech - Extended Edition (hbm)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
	at com.hbm.util.I18nUtil.resolveKey(I18nUtil.java:8)
	at com.hbm.items.machine.ItemRBMKRod$EnumBurnFunc.<clinit>(ItemRBMKRod.java:273)
	at com.hbm.items.machine.ItemRBMKRod.<init>(ItemRBMKRod.java:33)
	at com.hbm.items.machine.ItemRBMKRod.<init>(ItemRBMKRod.java:74)
	at com.hbm.items.ModItems.<clinit>(ModItems.java:2736)
	at com.hbm.main.MainRegistry.preInit(MainRegistry.java:554)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.resources.I18n
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 41 more
Caused by: java.lang.NullPointerException

Rolling back to the previous update alleviates the issue.

**Comment by Consumedgrub2** [comment]
Bump, I'm having the same issue with no other mods installed, fresh server, just HBM NTM extended 2.0.0

**Comment by FadeTNT1** [comment]
A patch will be out to fix this bug

In a few days 

apparently it tries to do a translation that Has to be client side not server side

**Comment by LukeMedia** [comment]
Fixed in most recent update.

**Comment by LukeMedia** [comment]
Reopening because the error has popped up again, same error but happens at a different time. Now occurs when clients join the game rather than during startup.

**Comment by Alcatergit** [comment]
Fixed it - will be in next update
