### ISSUE TITLE
Fresh Server install [Crash on startup] (No other mods, just NTM 2.0.0) [Duplicate]

### ISSUE THREAD

**Issue by Consumedgrub2** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#306]
I get this error on a regular forge server with no other mods, just only HBM NTM version 2.0.0. (The one that basically just came out) (Crash log attached) The server crashes immediately when HBM NTM Extended is loaded during fml load process.

```---- Minecraft Crash Report ----
// You're mean.

Time: 2/9/24 1:46 AM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from HBM's Nuclear Tech - Extended Edition (hbm)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
	at com.hbm.util.I18nUtil.resolveKey(I18nUtil.java:8)
	at com.hbm.items.machine.ItemRBMKRod$EnumBurnFunc.<clinit>(ItemRBMKRod.java:273)
	at com.hbm.items.machine.ItemRBMKRod.<init>(ItemRBMKRod.java:33)
	at com.hbm.items.machine.ItemRBMKRod.<init>(ItemRBMKRod.java:74)
	at com.hbm.items.ModItems.<clinit>(ModItems.java:2736)
	at com.hbm.main.MainRegistry.preInit(MainRegistry.java:554)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.resources.I18n
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 42 more
Caused by: java.lang.NullPointerException


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_401, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 7388379000 bytes (7046 MB) / 7591165952 bytes (7239 MB) up to 15068037120 bytes (14370 MB)
	JVM Flags: 1 total; -Xms6G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID        | Version                   | Source                        | Signature                                |
	|:----- |:--------- |:------------------------- |:----------------------------- |:---------------------------------------- |
	| LCH   | minecraft | 1.12.2                    | minecraft.jar                 | None                                     |
	| LCH   | mcp       | 9.42                      | minecraft.jar                 | None                                     |
	| LCH   | FML       | 8.0.99.99                 | forge-1.12.2-14.23.5.2860.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge     | 14.23.5.2860              | forge-1.12.2-14.23.5.2860.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCE   | hbm       | NTM-Extended-1.12.2-2.0.0 | NTM-Extended-1.12.2-2.0.0.jar | None                                     |

	Loaded coremods (and transformers): 
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)```

**Comment by Consumedgrub2** [comment]
[crash-2024-02-09_01.46.29-server.txt](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/files/14219674/crash-2024-02-09_01.46.29-server.txt)

**Comment by Consumedgrub2** [comment]
Sorry about this post, this was already stated in #300

**Comment by FadeTNT1** [comment]
A patch will be out to fix this bug

In a few days 

apparently it tries to do a translation that Has to be client side not server side
